### ISSUE TITLE
How to Add events to the Google calendar in Android (Expo)? 

### ISSUE THREAD

**Issue by toandevnguyen** [AtilaDev-team/my-expo-agenda#4]
The default calendar app on Android is Google Calendar. I followed your instructions, but when I click on the "add event" button, it only shows a permission grant notification and then nothing happens, no calendar shows up, no action no errors!

**Comment by AtilaDev** [comment]
> The default calendar app on Android is Google Calendar. I followed your instructions, but when I click on the "add event" button, it only shows a permission grant notification and then nothing happens, no calendar shows up, no action no errors!

Hi dude, the hook is working as expected in both platforms: Android and iOS.
Maybe you could share your code to help you.
